### ISSUE TITLE
More declarative approach to settings extra args?

### ISSUE THREAD

**Issue by kuator** [creativenull/efmls-configs-nvim#108]
https://github.com/creativenull/efmls-configs-nvim/blob/20fa61159a9a1c2b2d12e9d0a99bcfb0da8adf18/lua/efmls-configs/formatters/stylua.lua#L9C26-L9C26

I want to add `--indent-type Spaces --indent-width 2` to the `stylua` command.

What I do now:
```
  local stylua = require("efmls-configs.formatters.stylua")
  local fs = require("efmls-configs.fs")

  local formatter = "stylua"

  local command = string.format(
    "%s  --indent-type Spaces --indent-width 2 --color Never ${--range-start:charStart} ${--range-end:charEnd} -",
    fs.executable(formatter)
  )

  stylua["command"] = command
```
Maybe there should be some `extraArgs` option which we can pass custom arguments to?

**Comment by creativenull** [comment]
It was something I was thinking about adding initially but I ended not doing it because it was going to be complex. So I decided to just keep it as is, since it is simpler to modify it according to the user, so I have no plans of changing this.

However, I would suggest to try to use a `stylua.toml` first in your project and provide the changes (indent type, width, etc) in there before changing on the nvim config level.

I'm open to any suggestions on how to approach the `extraArgs` though.

**Comment by kuator** [comment]
> It was something I was thinking about adding initially but I ended not doing it because it was going to be complex. So I decided to just keep it as is, since it is simpler to modify it according to the user, so I have no plans of changing this.
> 
> However, I would suggest to try to use a `stylua.toml` first in your project and provide the changes (indent type, width, etc) in there before changing on the nvim config level.
> 
> I'm open to any suggestions on how to approach the `extraArgs` though.

I'm coming from a null-ls background. And null-ls had an `extra_args` option: https://github.com/jose-elias-alvarez/null-ls.nvim/blob/0010ea927ab7c09ef0ce9bf28c2b573fc302f5a7/doc/BUILTIN_CONFIG.md?plain=1#L119
Honestly, it's not a big deal to me, a user can simply edit a few lines in their config.
