### ISSUE TITLE
Prettier, Prettierd: tabWidth property in the config file's ignored 

### ISSUE THREAD

**Issue by HeRo3S** [creativenull/efmls-configs-nvim#118]
Hi, i'm trying to config efm using your config file for prettierd,
This is how i implemented my config before:

```
local eslint = require("efmls-configs.linters.eslint")
local prettier_d = require("efmls-configs.formatters.prettier_d")

local languages = {
	typescript = {eslint, prettier_d },
	javascript = { eslint, prettier_d },
}

local efmls_config = {
	filetypes = vim.tbl_keys(languages),
	settings = {
		rootMarkers = { ".git/" },
		languages = languages,
	},
	init_options = {
		documentFormatting = true,
		documentRangeFormatting = true,
	},
}

require("lspconfig").efm.setup(vim.tbl_extend("force", efmls_config, {}))

```
Everything's good so far except for the indent size.
I looked into the source code and noted that you are using the tabSize variable for tab-width argument. AFAIK the correct property for prettier's config file is tabWidth
By changing it to tabWidth i got the indent working properly: 

```
local languages = {
	typescript = {eslint, 	
	{
			formatCommand = "prettierd ${INPUT} ${--tab-width:tabWidth} ${--use-tabs:!insertSpaces} ${--range-start=charStart} ${--range-start=charEnd}",
			formatStdin = true,
		},
	},
	javascript = { eslint, prettier_d },
}
```

Am i doing something wrong here?

**Comment by creativenull** [comment]
You're not wrong, looks like it is `tabWidth` instead of `tabSize`. I'm guessing we were following the [`FormattingOptions`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#formattingOptions) of the LSP spec but didn't see the examples.

https://github.com/mattn/efm-langserver/blob/master/schema.md#languages_pattern1_items_format-command

PR is welcome if you want to fix this for prettier and prettierd

**Comment by HeRo3S** [comment]
Thanks for the reply.
I'll make a PR as soon as possible!

**Comment by creativenull** [comment]
Merged
