### ISSUE TITLE
golangci_lint linter not working when used from efmls

### ISSUE THREAD

**Issue by chama-chomo** [creativenull/efmls-configs-nvim#127]
When I remove '--out-format tab ' from the lint command it starts working

```
local golangci_lint = require("efmls-configs.linters.golangci_lint")
golangci_lint = vim.tbl_extend("force", golangci_lint, {
lintCommand = 'golangci_lint run --color never "${INPUT}"',
})
```

**Comment by creativenull** [comment]
Have you tried it in the terminal?

The command seems to work for me. Note that you will have to save to file in order to see the errors since `golangci-lint` does not read the file from stdin.

<img width="893" alt="image" src="https://github.com/creativenull/efmls-configs-nvim/assets/3767728/593c9170-2085-49b6-ad5c-89420069de86">

**Comment by chama-chomo** [comment]
I think I know what's the problem, if e.g. struct definition and its methods are spread across multiple files and i only give one file for the analysis golangci-lint loses its context, so some files are problematic running golangci-lint even from terminal. 
Anyway, I'm not able to reproduce it, anymore, so I'll close it
thanks!
