### ISSUE TITLE
Fish shell script linting with fish --no-execute

### ISSUE THREAD

**Issue by mrjones2014** [creativenull/efmls-configs-nvim#20]
Creating this issue to track a couple things I've already tried.

There are a few issues I've identified why I _think_ it doesn't work by default (but I'm not sure).

First, `fish --no-execute` outputs a code-window like so:

```
path/to/script.fish (line 5): Missing end to balance this function definition
function my-function
^~~~~~~^
warning: Error while reading file path/to/script.fish
```

But we only want to parse the first line with `errorformat`.

Second issue is that it only reports line, not column, but I think column is required? It also doesn't report an error level, which I think is also required.

`null-ls` worked around these by just defaulting column to `0` if it was `nil`, and skipping over any lines that fail to parse with `errorformat`.

I've got a modified `lintCommand` that attempt to fix these issues by:

- prefix each output line with `e:` so we can parse the error level as `error`
- modify the `(line 5)` to default column to 0 like `(line 5, col 0)`

The `lintCommand` I came up with is: 

```
fish --no-execute path/to/script.fish 2>&1 >/dev/null | awk '/\(line [0-9]+):/ { sub(/\)/, ", col 0):"); print "e:" $0 }'
```

Which gives output like:

```
e:path/to/script.fish (line 5, col 0):: Missing end to balance this function definition
```

which I then tried to parse with `lintFormats = { '%t:%f (line %l, col %c):: %m' }`

But I am still not getting diagnostics in the editor.

Any ideas how I can further debug this?

**Comment by creativenull** [comment]
Tried out the test code, I don't think you need to do any of that. `errorformat` will set the column number to 0.

Here is the format I did for it to work:

```
lintFormats = { '%.%#(line %l): %m' }
```

`%f` doesn't work because it's looking for a full path to the filename, but the output does not. So with `%.%#` it just matches anything (kinda like `.*` in regex).

However, it'd be nice to make use of multi-line format (check out `:help errorformat-multi-line`) so that we can parse the column number using the `%p` specifier (which reads the `----^` format). It's something I haven't extensively used 😅

**Comment by mrjones2014** [comment]
Oh, awesome! I'll submit a PR with this change.
