### ISSUE TITLE
health check crashes on nightly

### ISSUE THREAD

**Issue by MariaSolOs** [creativenull/efmls-configs-nvim#32]
When running `:checkhealth` with `neovim` nightly, the following errors appear:

<img width="793" alt="image" src="https://github.com/creativenull/efmls-configs-nvim/assets/62502207/2c293d12-1d4e-4117-94c4-7f2d04b93d08">

<img width="1203" alt="image" src="https://github.com/creativenull/efmls-configs-nvim/assets/62502207/112088c2-f104-4ecc-b435-03e3e99be85a">

**Comment by MariaSolOs** [comment]
Despite the errors, I do see the checks pass:
<img width="772" alt="image" src="https://github.com/creativenull/efmls-configs-nvim/assets/62502207/89c0bfa8-4221-4689-8dbc-d50b72231589">

And the stack traces seem to be referring to [this check](https://github.com/creativenull/efmls-configs-nvim/blob/5437658520d2aa35f118d3b18e0cbfa4dfd9db2c/autoload/health/efmls_configs.vim). Why is that file needed? [The docs](https://neovim.io/doc/user/pi_health.html#health-dev) say that the one in `health/init.lua` should be enough.

**Comment by creativenull** [comment]
The .vim health file is needed to be compatible with neovim 0.5 since it didn't have the lua health module.

I will plan to bump this min version to 0.7.2 (version available on ubuntu) on the [v1 release](https://github.com/creativenull/efmls-configs-nvim/pull/30) and remove the vimscript function for healthcheck, which I'm hoping to do that this week.

In the meantime, you'll just have to stick with the stable release if you're not able to properly make use of `:checkhealth`.

**Comment by MariaSolOs** [comment]
@creativenull I understand. Thank you for explaining!

> In the meantime, you'll just have to stick with the stable release if you're not able to properly make use of :checkhealth.

Sorry, I didn’t get this part. In the stable release (ie what’s on `main`) is causing the error, so how can this help?

**Comment by MariaSolOs** [comment]
> Sorry for the confusion, I was referring to the neovim stable release which is 0.9.1 not this plugin release.

Oh got it! I like using nightly hehe, so I’ll just be waiting for this plugin’s `v1` release :)

**Comment by creativenull** [comment]
I've merged [v1 changes](3c274bb64290a5c65987c29e8eb6d4df368a8d20) please check if the problem still persists, in the meantime I will close this issue.
