### ISSUE TITLE
Pint php formatter writes output to buffer

### ISSUE THREAD

**Issue by loci1559** [creativenull/efmls-configs-nvim#78]
When using the pint formatter, instead of keeping the formatted file in the buffer, the output of the pint command is shown.

**Comment by creativenull** [comment]
This is a known issue from efm-langserver (https://github.com/mattn/efm-langserver/issues/258#issuecomment-1699420945) it will output anything from stdout, I'm not aware of any option to help fix/ignore this.

The only I know is to run `:edit!` afterwards to get the updated buffer.

This happens because formatters like `pint` directly save the changes to the file which is not tracked by neovim unless you force a refresh (which in this case is `:edit!`).

**Comment by creativenull** [comment]
Closing this as it is a efm-langserver issue but will add a note on how to get around this.
