### ISSUE TITLE
Use project installed ESLint

### ISSUE THREAD

**Issue by AntDavidLima** [creativenull/efmls-configs-nvim#99]
Shouldn't efmls recognize the ESLint executable installed on my project and use it to send diagnostics?

When I run `:checkhealth efmls-configs` it says that no local or global ESLint executables were found. Installing eslint_d from Mason doesn't work as well.

The Prettier installed from Mason is recognized. 

I'm using Mason's emf and efmls-configs.defaults settings. Here are my configs:
```lua
require("mason-lspconfig").setup({
    ensure_installed = { "lua_ls", "tailwindcss", "efm", "eslint" },
})
require("mason-lspconfig").setup_handlers({
    function(server_name)
        require("lspconfig")[server_name].setup({
	    capabilities = require("cmp_nvim_lsp").default_capabilities(),
        })
    end,
    ["efm"] = function()
	local languages = require("efmls-configs.defaults").languages()

	require("lspconfig").efm.setup(vim.tbl_extend("force", {
	    filetypes = vim.tbl_keys(languages),
		settings = {
		    rootMarkers = { ".git/" },
		    languages = languages,
		},
		init_options = {
		    documentFormatting = true,
		    documentRangeFormatting = true,
		},
	}, {}))
    end,
})
```

I'm pretty noob with Neovim and tooling, so I'm not sure if this is actually unexpected behavior or if this issue should come here or in `mattn/efm-langserver` repo.

**Comment by creativenull** [comment]
Hmm this is weird, it should work out of box with mason.nvim.

Are you in the project directory when you open `nvim`? You have to be in the project directory for it to pick up eslint install to `node_modules`.

Could you also check some things:

- Run `:!which eslint` command inside nvim, it should either print out the path of eslint binary if installed via mason
- Make sure you're not running the eslint lsp server, this is different to eslint run by efm, `:LspInfo` should only show `efm` and maybe `tsserver` but not `eslint`
- Scoped it down to just eslint in your `languages`

```lua
local eslint = require('efmls-configs.linters.eslint')
local languages = {
  javascript = { eslint },
  typescript = { eslint },
}
```

And then run `:lua =vim.lsp.get_active_clients({ name = 'efm' })` and verify the settings property has the setup you have.

**Comment by AntDavidLima** [comment]
I thought `ahmedkhalf/project.nvim` was cding into my project directory for me, because when I run `:!pwd` it prints the correct work directory, but to be sure I opened nvim from the directory, and it just worked.

Thanks for your help and congratulations on the project, it was really great to find this when I heard about the null-ls archiving.

**Comment by creativenull** [comment]
Glad you enjoy it 🙂 

Don't forget there is [none-ls](https://github.com/nvimtools/none-ls.nvim) which is a fork in case it doesn't work out. I should put this in the readme 🤔

**Comment by AntDavidLima** [comment]
Sorry for reopening the issue, but since I don't think I'm getting any help soon on `ahmedkhalf/project.nvim`issues, I will for some help here.
`ahmedkhalf/project.nvim` changes my cwd, since the result of `:pwd` is the same as the project I'm working in, what sould br changed to efmls use my project installed ESLint and Prettier?

**Comment by creativenull** [comment]
Hmm I would check if `:pwd` is in the project and not `:!pwd` which is the current working directory of the terminal/shell.

But outside of that I can only recommend to cd into the project for it to pick up your eslint and prettier setup.

**Comment by AntDavidLima** [comment]
Yeah, the result of `:!pwd` and `:pwd` is the same.

I would like it to work when I open the project with `ahmedkhalf/project.nvim`, I don't like to first try to remember the path of the project, then cd into it and only then open Neovim every time I want to change projects, but thanks for the help anyway.

**Comment by creativenull** [comment]
I see where the problem is now, seems like your `efm` config is on your user config. Hence, the efmls-configs is being executed (for path checking) as soon as you open nvim.

I've browsed the project.nvim plugin and don't see that they have any hooks for you to run some custom logic after you've switched to a project dir (where you could run the efm lspconfig setup).

I think you should use `DirChanged` autocmd to then run `efm` setup config in it, instead of setting up `efm` in your main config.

What I mean is, listen to a `DirChanged` event and then run `require('lspconfig').efm.setup()` inside that event. Of course, you will need some extra logic to know which project should run efm.

This is similar to what I do with my project plugin ([creativenull/projectlocal.vim](https://github.com/creativenull/projectlocal.vim)) where I setup a file on my project directory which will be executed when I cd into the directory (whether from terminal or from inside nvim). But fundamentally different to how project.nvim does it 😅
